from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class TransparencyLabel:
    title: str
    message: str


AI_LABEL = TransparencyLabel(
    title="AI-Generated (High Confidence)",
    message=(
        "Our system found strong evidence that this content was generated using artificial intelligence. Confidence: High."
    ),
)

HUMAN_LABEL = TransparencyLabel(
    title="Human-Written (High Confidence)",
    message=(
        "Our system found strong evidence that this content was written by a human author. Confidence: High."
    ),
)

UNCERTAIN_LABEL = TransparencyLabel(
    title="Attribution Uncertain",
    message=(
        "Our system found mixed evidence and cannot confidently determine whether this content was written by a human or generated by AI."
    ),
)


def generate_transparency_label(confidence: float) -> TransparencyLabel:
    if confidence <= 0.39:
        return HUMAN_LABEL
    if confidence >= 0.61:
        return AI_LABEL
    return UNCERTAIN_LABEL
