from labels import AI_LABEL, HUMAN_LABEL, UNCERTAIN_LABEL, generate_transparency_label


def main() -> None:
    assert generate_transparency_label(0.0) == HUMAN_LABEL
    assert generate_transparency_label(0.39) == HUMAN_LABEL
    assert generate_transparency_label(0.40) == UNCERTAIN_LABEL
    assert generate_transparency_label(0.60) == UNCERTAIN_LABEL
    assert generate_transparency_label(0.61) == AI_LABEL
    assert generate_transparency_label(1.0) == AI_LABEL

    assert AI_LABEL.title == "AI-Generated (High Confidence)"
    assert (
        AI_LABEL.message
        == "Our system found strong evidence that this content was generated using artificial intelligence. Confidence: High."
    )

    assert HUMAN_LABEL.title == "Human-Written (High Confidence)"
    assert (
        HUMAN_LABEL.message
        == "Our system found strong evidence that this content was written by a human author. Confidence: High."
    )

    assert UNCERTAIN_LABEL.title == "Attribution Uncertain"
    assert (
        UNCERTAIN_LABEL.message
        == "Our system found mixed evidence and cannot confidently determine whether this content was written by a human or generated by AI."
    )

    print("labels ok")


if __name__ == "__main__":
    main()
